### ISSUE TITLE
Milestone 2: Working study and restroom locations

### ISSUE THREAD

**Issue by brian-w-ai** [ucsb-codepath-team5/ucsb_amenities#13]
# User Story

As a user, I want to be able to select study locations and bring them up in the map, and or bring up the details. 

# Discussion
We will need to implement the map controller with a search function maybe, and then the LocationCell will take the user to the map location. This might need to work differently with restrooms since the locations are a bit more specific. 

# Acceptance Criteria

- [ ] User is taken to the map with the correct location pinned. 

# Implementation Todos

- [ ] Implement the map tab first (search bar that brings up a tableview of location names, pins location when selected)
- [ ] Implement ability to change to map tab correctly
