### ISSUE TITLE
Milestone 2: Working Map Tab

### ISSUE THREAD

**Issue by brian-w-ai** [ucsb-codepath-team5/ucsb_amenities#14]
# User Story
As a user, I would like to be able to search up locations I remember in the map tab and have the location pinned onto the map so I can navigate to them. I would also like to have my location shown. 

# Discussion 
We have several options for this, we can either use google maps, apple maps, or any other map API, when we decide on this, please update this so it discusses the details of the API

# Acceptance Criteria
- [ ] User can see a map of the campus, can zoom in, etc 
- [ ] User can search for locations (based on the sheety backend info)
- [ ] User can see pinned locations as well as their own location

# Implementations To-Do's
- [ ] Choose an API to use for the map
- [ ] Add a tableview? (may be something else) with the search feature
