### ISSUE TITLE
Milestone 1: User can view study locations 

### ISSUE THREAD

**Issue by brian-w-ai** [ucsb-codepath-team5/ucsb_amenities#4]
- [x] Create tableview for main page
- [x] Create study cells for tableview as well as corresponding class
- [x] Cells should contain text for the study location information as well as a thumbnail 
- [ ] Optional: Tap to open features page (like Flix)
- [ ] Optional: Drop Down Filter -- https://www.youtube.com/watch?v=FJuSezRmEQI
https://github.com/AssistoLab/DropDown
